version: "3.8"

services:
  DevOpsProject:
    container_name: devops_project
    build: .
    ports:
      - "8082:8082"
    image: devops_project  # Changed to lowercase
    hostname: devops_project
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db2_mysql:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - docker-mysql_2

  docker-mysql_2:
    image: "mysql:5.6"
    container_name: db2_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=devops
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3310:3306"
